#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 #f)
         (x1 (lambda (x) x0))
         (x2 (cons #f x0))
         (x3 -1)
         (x4 (cons x0 x3))
         (x5 (cons x3 x3))
         (x6
          (lambda (x)
            (if (= x 0)
              x0
              (if (= x 1)
                x1
                (if (= x 2) x2 (if (= x 3) x0 (if (= x 4) x0 x3)))))))
         (x7 (cons x0 #f)))
    (set-first! x2 x6)
    (set-rest! x7 x7)
    x5))
(define (traverse-one x5) (= -1 (first x5)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
