#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 #f)
         (x1 (cons #f #f))
         (x2 empty)
         (x3 (cons #f x2))
         (x4 (cons x2 #f))
         (x5 -1)
         (x6 'x)
         (x7 (cons x6 x5)))
    (set-first! x1 x6)
    (set-rest! x1 x7)
    (set-first! x3 x3)
    (set-rest! x4 x4)
    x1))
(define (traverse-one x1) (symbol=? 'x (first (rest x1))))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
