#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 #t)
         (x1 empty)
         (x2 'y)
         (x3
          (lambda (x)
            (if (= x 0)
              x1
              (if (= x 1)
                x2
                (if (= x 2) x2 (if (= x 3) x1 (if (= x 4) x0 x1)))))))
         (x4 (cons #f #f))
         (x5 'x)
         (x6 empty)
         (x7 'y)
         (x8 'x))
    (set-first! x4 x5)
    (set-rest! x4 x8)
    x3))
(define (traverse-one x3) (let ((res (x3 4))) (if (boolean? res) res #f)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
