#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 empty)
         (x1 -1)
         (x2 (cons #f #f))
         (x3 'x)
         (x4 empty)
         (x5 (cons x1 x2))
         (x6 (cons x2 x5))
         (x7 (lambda (x) (if (= x 0) x2 x2)))
         (x8 (cons #f x5))
         (x9 (cons x1 x7)))
    (set-first! x2 x7)
    (set-rest! x2 x7)
    (set-first! x8 x9)
    x3))
(define (traverse-one x3) (symbol=? 'x x3))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
