#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 #f)
         (x1 (cons #f #f))
         (x2 (lambda (x) (if (= x 0) x1 (if (= x 1) x1 (if (= x 2) x1 x1))))))
    (set-first! x1 x2)
    (set-rest! x1 x1)
    x0))
(define (traverse-one x0) (if x0 #f #t))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
