#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 'y)
         (x1 (lambda (x) (if (= x 0) x0 (if (= x 1) x0 (if (= x 2) x0 x0)))))
         (x2 (cons x1 #f)))
    (set-rest! x2 x2)
    x2))
(define (traverse-one x2)
  (symbol=? 'y ((first (rest (rest (rest (rest (rest (rest x2))))))) 0)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
