#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 'x)
         (x1 (cons #f #f))
         (x2 0)
         (x3 (cons x2 #f))
         (x4 empty)
         (x5 empty))
    (set-first! x1 x5)
    (set-rest! x1 x2)
    (set-rest! x3 x5)
    x3))
(define (traverse-one x3) (= 0 (first x3)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
