#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 #f)
         (x1 (cons #f #f))
         (x2 (cons #f #f))
         (x3 1)
         (x4 #f)
         (x5 #f)
         (x6 (cons x3 x2)))
    (set-first! x1 x5)
    (set-rest! x1 x6)
    (set-first! x2 x4)
    (set-rest! x2 x6)
    x2))
(define (traverse-one x2) (if (first (rest (rest x2))) #f #t))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
