#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 1)
         (x1 (lambda (x) (if (= x 0) x0 x0)))
         (x2 (cons #f #f))
         (x3 'y)
         (x4 (cons x1 x3))
         (x5 (cons x3 x4))
         (x6 1))
    (set-first! x2 x5)
    (set-rest! x2 x2)
    x2))
(define (traverse-one x2) (= 1 ((first (rest (first (rest x2)))) 0)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
