#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 1) (x1 'y) (x2 (cons x0 #f)) (x3 empty) (x4 (cons x3 x2)))
    (set-rest! x2 x3)
    x1))
(define (traverse-one x1) (symbol=? 'y x1))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
