#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 1)
         (x1 0)
         (x2 (cons x1 #f))
         (x3 (cons #f x2))
         (x4
          (lambda (x)
            (if (= x 0)
              x2
              (if (= x 1) x0 (if (= x 2) x0 (if (= x 3) x1 x0))))))
         (x5 (lambda (x) (if (= x 0) x2 (if (= x 1) x0 (if (= x 2) x1 x0)))))
         (x6 -1))
    (set-rest! x2 x5)
    (set-first! x3 x5)
    x3))
(define (traverse-one x3) (= 1 ((rest (rest x3)) 3)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
