#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 -1)
         (x1 (cons #f #f))
         (x2 #t)
         (x3 #f)
         (x4 empty)
         (x5 'y)
         (x6 (cons x4 x1)))
    (set-first! x1 x4)
    (set-rest! x1 x1)
    x6))
(define (traverse-one x6) (empty? (first x6)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
