#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 empty)
         (x1 -1)
         (x2 1)
         (x3 (lambda (x) (if (= x 0) x0 (if (= x 1) x2 x0))))
         (x4 1)
         (x5 (cons x3 x0))
         (x6 'x))
    x6))
(define (traverse-one x6) (symbol=? 'x x6))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
