#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 empty)
         (x1 (cons x0 #f))
         (x2 (cons x0 #f))
         (x3 (cons #f #f))
         (x4 (lambda (x) (if (= x 0) x0 x0)))
         (x5 #t)
         (x6 -1)
         (x7 1)
         (x8 (lambda (x) (if (= x 0) x7 x7))))
    (set-rest! x1 x5)
    (set-rest! x2 x4)
    (set-first! x3 x6)
    (set-rest! x3 x5)
    x3))
(define (traverse-one x3) (= -1 (first x3)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
