#lang plai/gc2/mutator
(allocator-setup "coll.rkt" 200)
(define (build-one)
  (let* ((x0 'y) (x1 (cons #f #f)) (x2 (cons x0 #f)))
    (set-first! x1 x2)
    (set-rest! x1 x2)
    (set-rest! x2 x2)
    x1))
(define (traverse-one x1) (symbol=? 'y (first (first x1))))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
